### ISSUE TITLE
Haze vanishes without fallback tint after navigation transition

### ISSUE THREAD

**Issue by trdin** [chrisbanes/haze#734]
## Information

- Haze version: 1.6.9 (appeared in older versions too)
- Platform: Android
- Platform version: Android 15
- Specific device: Pixel 8a, Samsung galaxy s23

## Expected Behavior

Haze normally shown on the top bar

## Actual Behavior

Here is one example of haze vanishing (top bar). It happens only after I added the Cast button. This is just one scenario in which it disappears. In my actual app, I use it on multiple screens, and there it also vanishes without showing the fallback tint. I guess those screens are heavier in computation (observing states, updating UI, injecting multiple view models). The issue is much more frequent in my actual app, but clicking around in the demo app I provided should trigger it within a minute or so.

https://github.com/user-attachments/assets/0ca09b8b-285e-4fa6-8f93-3eb0c551c772

## Steps to Reproduce the Problem

Please include reproducible code where possible

  1. Navigate multiple times 
  2. Trigger navigation transitions

source code: https://github.com/trdin/HazeIssue/tree/haze-vanishes

Would really appreciate it if you could take a look when you have time. Let me know if there's anything else I can provide. Thank you!

**Comment by trdin** [comment]
I am attaching the video again. Is it possible to at least show the fallback tint instead ? Do you have any advice how do i avoid this ? 

https://github.com/user-attachments/assets/de0f0fba-8b45-4374-9de9-33361e4fc44a

(It also seems to vanish if the details screen is  "computing heavy"; the top bar on main screen vanishes, but thats another scenario)

**Comment by Plovotok** [comment]
I have never encountered this bug in compose 1.9. Maybe fixed in new compose version

**Comment by Plovotok** [comment]
@trdin Oh, I'm using v1. 6.6

**Comment by enel1989** [comment]
> [@enel1989](https://github.com/enel1989) i did not have this library i added it and it did not help unfortunately, but thank you anyway. If possible could you provide you `libs.versions.toml` file, i would like to check if its really the problem with libraries in my case.

I've just checked your code and it uses way older compose bom, so maybe I have a different issue that results the same problem. I'll also create a sample app soon and send it to here.

**Comment by trdin** [comment]
@enel1989 i'm sorry i was talking about testing with my main application, here i posted the sample, but still even with upgrading BOM to your version and upgrading compose to 1.9. I can still reproduce the issue in my sample

**Comment by Dimezis** [comment]
@chrisbanes 
> As a guess, it might be that the system is clearing the GraphicsLayer (RenderNode) under high memory pressure.

Is that a documented behavior? 
That seems highly unlikely, considering every View internally uses RenderNodes for rendering since API 21.

**Comment by trdin** [comment]
Hi! There was probably an issue on my end with the release build. I retried after upgrading Compose to 1.9 and it works. I’ve tested it a lot since then, and the issue seems resolved. No more vanishing! :tada:

**Comment by Dimezis** [comment]
I think there was a legit bug in Compose before 1.9, it's also working fine for me on 1.9

**Comment by chrisbanes** [comment]
Cool, I'm going to close this. Thanks for checking!
